import { asc,eq } from "drizzle-orm";import { getDb } from "../../../db";import { products } from "../../../db/schema";import { getAdminAccess } from "../../admin-auth";
const fail=(e:unknown,fallback:string)=>Response.json({error:e instanceof Error?e.message:fallback},{status:500});
export async function GET(){try{const db=getDb();const rows=await db.select().from(products).where(eq(products.active,true)).orderBy(asc(products.id));return Response.json({products:rows.map(row=>({...row,imageUrl:row.imageUrl||null}))})}catch(e){return fail(e,"Não foi possível carregar os produtos")}}
async function requireMaster(){const access=await getAdminAccess();return access?.role === "master" ? access : null}
export async function POST(request:Request){if(!await requireMaster())return Response.json({error:"Não autorizado"},{status:401});try{const b=await request.json();const db=getDb();const [product]=await db.insert(products).values({name:String(b.name),category:String(b.category),price:Number(b.price),description:String(b.description),imageUrl:b.imageUrl?String(b.imageUrl):null,featured:!!b.featured,publicVisible:b.publicVisible!==false,active:true}).returning();return Response.json({product},{status:201})}catch(e){return fail(e,"Erro")}}
export async function PATCH(request:Request){if(!await requireMaster())return Response.json({error:"Não autorizado"},{status:401});try{const b=await request.json();const id=Number(b.id);if(!Number.isInteger(id)||id<1)return Response.json({error:"Produto sem id válido. Recarregue a página e tente novamente."},{status:400});const db=getDb();const [product]=await db.update(products).set({name:String(b.name),category:String(b.category),price:Number(b.price),description:String(b.description),imageUrl:b.imageUrl?String(b.imageUrl):null,featured:!!b.featured,publicVisible:b.publicVisible!==false,active:b.active!==false}).where(eq(products.id,id)).returning();if(!product)return Response.json({error:`Produto ${id} não existe no banco.`},{status:404});return Response.json({product})}catch(e){return fail(e,"Erro")}}
// Remoção é desativação, não DELETE: os pedidos guardam o id do produto em
// orders.items e apagar a linha quebraria o histórico. Sair de active também
// libera o nome, já que o índice único cobre apenas os ativos.
export async function DELETE(request:Request){if(!await requireMaster())return Response.json({error:"Não autorizado"},{status:401});try{const id=Number(new URL(request.url).searchParams.get("id"));if(!Number.isInteger(id)||id<1)return Response.json({error:"Produto sem id válido."},{status:400});const db=getDb();const [product]=await db.update(products).set({active:false,publicVisible:false}).where(eq(products.id,id)).returning();if(!product)return Response.json({error:`Produto ${id} não existe no banco.`},{status:404});return Response.json({product})}catch(e){return fail(e,"Erro")}}
