BEGIN;

CREATE TABLE IF NOT EXISTS customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  clinic text,
  phone text NOT NULL,
  email text NOT NULL,
  cro text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  clinic text,
  phone text NOT NULL,
  email text,
  cro text,
  notes text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  price double precision NOT NULL,
  description text NOT NULL DEFAULT '',
  image_url text,
  featured boolean NOT NULL DEFAULT false,
  public_visible boolean NOT NULL DEFAULT true,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS staff (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  name text NOT NULL,
  password_hash text NOT NULL DEFAULT '',
  must_change_password boolean NOT NULL DEFAULT true,
  password_changed_at timestamptz,
  role text NOT NULL DEFAULT 'collaborator',
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS staff_email_unique ON staff (lower(email));

CREATE TABLE IF NOT EXISTS orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text,
  phone text,
  items text NOT NULL,
  total double precision NOT NULL,
  status text NOT NULL DEFAULT 'Aguardando confirmação',
  source text NOT NULL DEFAULT 'catalog',
  created_by text,
  client_id integer REFERENCES clients(id) ON DELETE SET NULL,
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id text PRIMARY KEY,
  staff_id integer NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  type text NOT NULL,
  status text,
  content text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status);
CREATE INDEX IF NOT EXISTS orders_created_at_idx ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS order_events_order_id_idx ON order_events(order_id);
CREATE INDEX IF NOT EXISTS admin_sessions_expires_at_idx ON admin_sessions(expires_at);

COMMIT;
