"use client";
import { useMemo, useState } from "react";
import { catalog, Product } from "./catalog";

type View="bio"|"cliente"|"admin"; type CartItem=Product&{qty:number};
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:0});

export default function OrtoFernandesApp(){
 const [view,setView]=useState<View>("bio"),[filter,setFilter]=useState("Todos"),[cart,setCart]=useState<CartItem[]>([]),[cartOpen,setCartOpen]=useState(false),[sent,setSent]=useState(""),[products,setProducts]=useState(catalog),[adminTab,setAdminTab]=useState("pedidos");
 const cats=["Todos",...Array.from(new Set(products.map(p=>p.category)))]; const shown=filter==="Todos"?products:products.filter(p=>p.category===filter); const total=cart.reduce((s,i)=>s+i.price*i.qty,0); const qty=cart.reduce((s,i)=>s+i.qty,0);
 const add=(p:Product)=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});
 const navigate=(v:View)=>{setView(v);window.scrollTo({top:0,behavior:"smooth"})};
 const submit=async(type:string,payload:Record<string,unknown>)=>{try{await fetch("/api/platform",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,...payload})})}catch{}setSent(type==="order"?"Pedido recebido! Nossa equipe confirmará os detalhes pelo WhatsApp.":"Cadastro criado! Você já pode aproveitar as vantagens de cliente.")};
 const order=()=>{submit("order",{items:cart,total});setCart([])};
 const orders=useMemo(()=>[{id:"#1048",client:"Clínica Sorriso",item:"Disjuntor de Hyrax",value:140},{id:"#1047",client:"Dra. Marina Lopes",item:"Contenção Hawley",value:70},{id:"#1046",client:"Odonto Prime",item:"Bionator c/ expansor",value:200}],[]);
 return <main className="shell">
  <header className="topbar"><button className="brand" onClick={()=>navigate("bio")} style={{border:0,background:"transparent"}}><i className="mark">OF</i><span><strong>ORTO FERNANDES</strong><span>LABORATÓRIO</span></span></button><nav className="nav"><button className={view==="bio"?"active":""} onClick={()=>navigate("bio")}>Pedir agora</button><button className={view==="cliente"?"active":""} onClick={()=>navigate("cliente")}>Área do cliente</button><button className={view==="admin"?"active":""} onClick={()=>navigate("admin")}>Admin</button></nav><a className="contact" href="https://wa.me/5591983160016">(91) 98316-0016</a></header>
  {view==="bio"&&<><section className="hero"><div><div className="eyebrow">Laboratório ortodôntico</div><h1>Precisão que transforma sorrisos.</h1><p>Aparelhos ortodônticos feitos com cuidado técnico, agilidade e atendimento próximo para dentistas e clínicas.</p><div className="actions"><button className="primary" onClick={()=>document.getElementById("catalogo")?.scrollIntoView()}>Fazer pedido rápido</button><button className="secondary" onClick={()=>navigate("cliente")}>Quero ser cliente</button></div><div className="trust"><span>Catálogo atualizado</span><span>Pedido pelo WhatsApp</span><span>Atendimento humano</span></div></div><aside className="hero-card"><div className="tag">Destaque do catálogo</div><h2>Qualidade e excelência em aparelhos ortodônticos</h2><div className="mini-product"><div className="product-orb">◒</div><div><strong>Disjuntor de Hyrax</strong><small>Aparelho ortodôntico fixo</small></div><span className="price">R$ 140</span></div></aside></section>
   <section className="section" id="catalogo"><div className="section-head"><div><div className="eyebrow">Catálogo 2026.2</div><h2>Escolha seu aparelho</h2></div><p>Selecione os itens e envie seu pedido. A equipe confirma os detalhes técnicos, prazo e entrega com você.</p></div><div className="filters">{cats.map(c=><button key={c} className={`chip ${filter===c?"active":""}`} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="catalog">{shown.map(p=><article className="product" key={p.id}><span className="cat">{p.category}</span><h3>{p.name}</h3><div className="product-bottom"><strong>{money(p.price)}</strong><button aria-label={`Adicionar ${p.name}`} className="add" onClick={()=>add(p)}>+</button></div></article>)}</div><div className="notice"><b>Importante:</b> para trabalhos com preço inferior a R$ 50, é cobrada taxa de R$ 20 para buscar e entregar.</div></section>
   <section className="benefits"><div className="benefits-inner"><div><div className="eyebrow" style={{color:"#8dbaff"}}>Vantagens para clientes</div><h2>Mais praticidade em cada pedido.</h2><p>Crie seu cadastro para concentrar pedidos, agilizar repetições e acompanhar cada trabalho.</p><button className="primary" onClick={()=>navigate("cliente")}>Criar meu cadastro</button></div><div className="benefit-grid"><div className="benefit"><span className="icon">◷</span><b>Histórico organizado</b><small>Consulte seus pedidos anteriores em um só lugar.</small></div><div className="benefit"><span className="icon">↻</span><b>Repita em segundos</b><small>Refaça pedidos frequentes sem preencher tudo de novo.</small></div><div className="benefit"><span className="icon">◎</span><b>Acompanhe o status</b><small>Veja a etapa de produção e a previsão de entrega.</small></div><div className="benefit"><span className="icon">✦</span><b>Atendimento prioritário</b><small>Seus dados e preferências ficam sempre à mão.</small></div></div></div></section></>}
  {view==="cliente"&&<section className="panel"><div className="card"><div className="eyebrow">Área do cliente</div><h2>Crie seu cadastro</h2><p className="muted">Tenha histórico, acompanhamento e pedidos recorrentes mais rápidos.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit("customer",Object.fromEntries(f))}}><div className="field"><label>Nome completo</label><input name="name" required placeholder="Seu nome"/></div><div className="field"><label>Clínica / Consultório</label><input name="clinic" placeholder="Nome da clínica"/></div><div className="field"><label>WhatsApp</label><input name="phone" required placeholder="(91) 99999-9999"/></div><div className="field"><label>E-mail</label><input name="email" type="email" required placeholder="voce@clinica.com"/></div><div className="field span2"><label>CRO / Cidade</label><input name="cro" placeholder="CRO-PA 0000 · Belém"/></div><button className="primary span2" type="submit">Criar meu cadastro</button></form>{sent&&<div className="success">{sent}</div>}</div></section>}
  {view==="admin"&&<section className="panel"><div className="card"><div className="eyebrow">Painel administrativo</div><h2>Visão geral</h2><p className="muted">Gerencie pedidos, catálogo e preços do link da bio.</p><div className="admin-stats"><div className="stat"><span>PEDIDOS HOJE</span><b>8</b></div><div className="stat"><span>EM PRODUÇÃO</span><b>14</b></div><div className="stat"><span>FATURAMENTO DO MÊS</span><b>R$ 6.480</b></div></div><div className="admin-tabs"><button className={adminTab==="pedidos"?"active":""} onClick={()=>setAdminTab("pedidos")}>Pedidos</button><button className={adminTab==="produtos"?"active":""} onClick={()=>setAdminTab("produtos")}>Produtos e preços</button></div>{adminTab==="pedidos"?<div className="admin-list">{orders.map(o=><div className="admin-row" key={o.id}><div><b>{o.client}</b><div className="muted">{o.id} · {o.item}</div></div><span className="status">Em produção</span><b>{money(o.value)}</b></div>)}</div>:<div className="admin-list">{products.slice(0,12).map(p=><div className="admin-row" key={p.id}><div><b>{p.name}</b><div className="muted">{p.category}</div></div><input aria-label={`Preço de ${p.name}`} style={{width:90,padding:8,border:"1px solid var(--line)",borderRadius:8}} type="number" value={p.price} onChange={e=>setProducts(ps=>ps.map(x=>x.id===p.id?{...x,price:Number(e.target.value)}:x))}/><b>{money(p.price)}</b></div>)}</div>}</div></section>}
  <footer className="footer"><span>© 2026 Laboratório Orto Fernandes</span><span>98535-6011 · 98316-0016</span></footer>
  {qty>0&&<button className="cartbar" onClick={()=>setCartOpen(true)}>Ver pedido · {qty} {qty===1?"item":"itens"} · {money(total)}</button>}
  {cartOpen&&<div className="modal-back" onMouseDown={e=>{if(e.target===e.currentTarget)setCartOpen(false)}}><div className="modal"><div className="modal-head"><div><div className="eyebrow">Pedido rápido</div><h2 style={{margin:"8px 0"}}>Revise seu pedido</h2></div><button className="close" onClick={()=>setCartOpen(false)}>×</button></div>{cart.length?cart.map(i=><div className="cart-item" key={i.id}><span>{i.qty}× {i.name}</span><b>{money(i.price*i.qty)}</b></div>):<div className="empty">Seu pedido está vazio.</div>}<div className="total"><span>Total</span><span>{money(total)}</span></div><div className="field"><label>Seu nome ou clínica</label><input placeholder="Como podemos chamar você?"/></div><div className="field" style={{marginTop:12}}><label>WhatsApp</label><input placeholder="(91) 99999-9999"/></div>{sent&&<div className="success">{sent}</div>}<button className="primary" style={{width:"100%",marginTop:16}} onClick={order} disabled={!cart.length}>Enviar pedido</button></div></div>}
 </main>
}
