"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { ArrowRight,BadgeCheck,BookOpen,MapPin,MessageCircle } from "lucide-react";
import { catalog,Product } from "../catalog";
const phone="5591985667411";
const wa=(message:string)=>`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
export default function BioPage(){const [products,setProducts]=useState<Product[]>(catalog);useEffect(()=>{fetch("/api/products").then(r=>r.ok?r.json():null).then(d=>d?.products&&setProducts(d.products)).catch(()=>{})},[]);const featured=products.filter(p=>p.active!==false&&p.publicVisible!==false&&p.featured).slice(0,8);return <main className="bio-page"><div className="bio-shell">
 <header className="bio-cover"><img src="/laboratorio-hero.jpg" alt="Aparelhos ortodônticos produzidos pelo Laboratório Orto Fernandes"/><div className="cover-shade"/></header>
 <section className="bio-profile"><div className="bio-avatar"><img src="/logo-orto.jpg" alt="Logo do Laboratório Orto Fernandes"/></div><p className="overline">LABORATÓRIO ORTODÔNTICO</p><h1>Orto Fernandes</h1><p className="bio-copy">Aparelhos ortodônticos feitos com precisão, acabamento e cuidado para dentistas e clínicas.</p><div className="bio-meta"><span><MapPin size={13}/> Belém e região</span><span><BadgeCheck size={13}/> Atendimento especializado</span></div></section>
 <section className="bio-actions"><a className="bio-main-action" href={wa("Olá! Vim pelo Instagram da Orto Fernandes e gostaria de receber o link do catálogo completo com preços.")} target="_blank"><span className="action-icon"><BookOpen size={20}/></span><span><b>Catálogo com preços</b><small>Solicite o acesso pelo WhatsApp</small></span><ArrowRight size={19}/></a><a className="bio-secondary-action" href={wa("Olá! Vim pelo Instagram da Orto Fernandes e gostaria de falar com a equipe.")} target="_blank"><MessageCircle size={18}/><span><b>Falar com a equipe</b><small>Atendimento pelo WhatsApp</small></span><ArrowRight size={17}/></a></section>
 <section className="bio-products"><div className="bio-section-title"><div><span>CONHEÇA NOSSO TRABALHO</span><h2>Aparelhos em destaque</h2></div><Link href="/catalogo">Ver todos <ArrowRight size={14}/></Link></div><div className="bio-product-list">{featured.map((p,i)=><article className="bio-product" key={p.id}><div className={`product-photo product-photo-${i%3}`}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<span>OF</span>}</div><div className="bio-product-info"><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><a href={wa(`Olá! Vim pelo Instagram da Orto Fernandes e gostaria de solicitar o produto “${p.name}”. Poderia me passar mais informações?`)} target="_blank">Solicitar informações <ArrowRight size={14}/></a></div></article>)}</div></section>
 <section className="about-strip"><span>DESDE O PRIMEIRO CONTATO</span><h2>Excelência em cada detalhe.</h2><p>Trabalhamos em parceria com profissionais para entregar aparelhos com acabamento, precisão e agilidade.</p></section>
 <footer className="bio-footer"><div className="footer-logo"><img src="/logo-orto.jpg" alt="Logo do Laboratório Orto Fernandes"/></div><p>Laboratório Orto Fernandes</p><span>98535-6011 · 98316-0016</span><div><Link href="/cliente">Área do cliente</Link><Link href="/admin">Administração</Link></div></footer>
 </div></main>}
