"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { catalog,Product } from "../catalog";

type CartItem=Product&{quantity:number};
const phone="5591985667411";
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const wa=(message:string)=>`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;

export default function CatalogPage(){
 const [products,setProducts]=useState<Product[]>(catalog),[filter,setFilter]=useState("Todos"),[query,setQuery]=useState(""),[cart,setCart]=useState<CartItem[]>([]),[open,setOpen]=useState(false),[customer,setCustomer]=useState(""),[sending,setSending]=useState(false),[sendError,setSendError]=useState(""),[whatsappLink,setWhatsappLink]=useState("");
 useEffect(()=>{fetch("/api/products").then(r=>r.ok?r.json():null).then(d=>d?.products&&setProducts(d.products)).catch(()=>{})},[]);
 const cats=["Todos",...Array.from(new Set(products.map(p=>p.category)))];
 const shown=useMemo(()=>products.filter(p=>p.active!==false&&p.publicVisible!==false&&(filter==="Todos"||p.category===filter)&&p.name.toLowerCase().includes(query.toLowerCase())),[products,filter,query]);
 const count=cart.reduce((sum,item)=>sum+item.quantity,0),total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);
 const add=(p:Product)=>setCart(items=>{const existing=items.find(i=>i.id===p.id);return existing?items.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...items,{...p,quantity:1}]});
 const change=(id:number,delta:number)=>setCart(items=>items.map(i=>i.id===id?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0));
 const orderMessage=(orderId?:number)=>{const lines=cart.map((item,index)=>`${index+1}. *${item.name}*\n   Quantidade: ${item.quantity}\n   Valor unitário: ${money(item.price)}\n   Subtotal: ${money(item.price*item.quantity)}`).join("\n\n");return `*SOLICITAÇÃO DE ENCOMENDA*\n*Laboratório Orto Fernandes*${orderId?`\n*Referência:* OF-${String(orderId).padStart(5,"0")}`:""}\n\nOlá! Consultei o catálogo e gostaria de solicitar um orçamento para os itens abaixo:\n\n${lines}\n\n────────────────────\n*Quantidade total:* ${count} ${count===1?"item":"itens"}\n*Valor estimado:* ${money(total)}\n────────────────────\n${customer?`*Solicitante:* ${customer}\n`:""}\nGostaria de confirmar a disponibilidade, o prazo de produção e as condições de entrega. Obrigado!`};
 const finishOrder=async()=>{setSending(true);setSendError("");setWhatsappLink("");let orderId:number|undefined,lastError="Não foi possível registrar o pedido.";const payload=JSON.stringify({customerName:customer,items:cart.map(({id,name,price,quantity})=>({id,name,price,quantity})),total});for(let attempt=0;attempt<2&&!orderId;attempt++){try{const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json","cache-control":"no-cache"},body:payload,cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok){lastError=data.error||`Falha no servidor (${response.status}).`;continue}orderId=data.order?.id;if(!orderId)lastError="O servidor não confirmou o número do pedido."}catch(error){lastError=error instanceof Error?error.message:lastError}}if(!orderId){setSendError(`${lastError} Atualize a página e tente novamente.`);setSending(false);return}const link=wa(orderMessage(orderId));setWhatsappLink(link);setSending(false);window.location.assign(link)};
 return <main className="catalog-page">
  <header className="catalog-header"><Link href="/" className="back">← Bio</Link><div className="catalog-brand"><span>OF</span><div><b>ORTO FERNANDES</b><small>CATÁLOGO COM PREÇOS</small></div></div><a href="https://wa.me/5591985667411" target="_blank">WhatsApp</a></header>
  <section className="catalog-intro"><span className="kicker">CATÁLOGO 2026.2</span><h1>Aparelhos ortodônticos</h1><p>Adicione quantos produtos quiser ao carrinho e envie uma única solicitação pelo WhatsApp.</p><input aria-label="Buscar produto" placeholder="Buscar aparelho..." value={query} onChange={e=>setQuery(e.target.value)}/></section>
  <div className="catalog-filters">{cats.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div>
  <section className="price-grid">{shown.map((p,i)=>{const inCart=cart.find(item=>item.id===p.id)?.quantity||0;return <article className="price-card" key={p.id}><div className={`price-image product-photo-${i%3}`}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<span>OF</span>}</div><div><small>{p.category}</small><h2>{p.name}</h2><p>{p.description}</p><div className="price-line"><strong>{money(p.price)}</strong><a href={wa(`Olá! Consultei o catálogo da Orto Fernandes e gostaria de encomendar “${p.name}”.`)} target="_blank">Pedir este</a></div><button className={`add-cart ${inCart?"added":""}`} onClick={()=>add(p)}>{inCart?`Adicionar mais · ${inCart} no carrinho`:`+ Adicionar ao carrinho`}</button></div></article>})}</section>
  <aside className="fee-note"><b>Importante</b><span>Para trabalhos com preço inferior a R$ 50, cobramos taxa de R$ 20 para buscar e entregar.</span></aside>
  <footer className="catalog-footer"><Link href="/">Voltar para a bio</Link><span>Laboratório Orto Fernandes · 98535-6011</span></footer>
  {count>0&&<button className="floating-cart" onClick={()=>setOpen(true)}><span className="cart-bag">▣</span><span><b>Ver carrinho</b><small>{count} {count===1?"item":"itens"}</small></span><strong>{money(total)}</strong></button>}
  {open&&<div className="cart-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="cart-drawer"><header><div><span className="kicker">SUA ENCOMENDA</span><h2>Revisar carrinho</h2></div><button onClick={()=>setOpen(false)} aria-label="Fechar carrinho">×</button></header><div className="cart-list">{cart.map(item=><article className="cart-row" key={item.id}><div><b>{item.name}</b><small>{money(item.price)} cada</small></div><div className="quantity"><button onClick={()=>change(item.id,-1)} aria-label={`Diminuir ${item.name}`}>−</button><span>{item.quantity}</span><button onClick={()=>change(item.id,1)} aria-label={`Aumentar ${item.name}`}>+</button></div><strong>{money(item.price*item.quantity)}</strong></article>)}</div><div className="cart-summary"><div><span>Itens</span><b>{count}</b></div><div><span>Valor estimado</span><b>{money(total)}</b></div></div><label className="customer-name">Nome ou clínica <input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Para identificar seu pedido"/></label>{sendError&&<p className="order-error">{sendError}</p>}<button className="finish-whatsapp" onClick={finishOrder} disabled={sending}><span>◉</span><span><b>{sending?"Registrando pedido...":"Enviar pedido pelo WhatsApp"}</b><small>O pedido será salvo antes de abrir a conversa</small></span></button><button className="clear-cart" onClick={()=>{setCart([]);setOpen(false)}}>Limpar carrinho</button></aside></div>}
 </main>
}
