import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const customers=sqliteTable("customers",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),clinic:text("clinic"),phone:text("phone").notNull(),email:text("email").notNull(),cro:text("cro"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const orders=sqliteTable("orders",{id:integer("id").primaryKey({autoIncrement:true}),customerName:text("customer_name"),phone:text("phone"),items:text("items").notNull(),total:real("total").notNull(),status:text("status").notNull().default("Aguardando confirmação"),source:text("source").notNull().default("catalog"),createdBy:text("created_by"),clientId:integer("client_id"),notes:text("notes"),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const products=sqliteTable("products",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),category:text("category").notNull(),price:real("price").notNull(),description:text("description").notNull().default(""),imageUrl:text("image_url"),featured:integer("featured",{mode:"boolean"}).notNull().default(false),publicVisible:integer("public_visible",{mode:"boolean"}).notNull().default(true),active:integer("active",{mode:"boolean"}).notNull().default(true)});

export const clients=sqliteTable("clients",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),clinic:text("clinic"),phone:text("phone").notNull(),email:text("email"),cro:text("cro"),notes:text("notes"),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const staff=sqliteTable("staff",{id:integer("id").primaryKey({autoIncrement:true}),email:text("email").notNull().unique(),name:text("name").notNull(),passwordHash:text("password_hash").notNull().default(""),role:text("role").notNull().default("collaborator"),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const adminSessions=sqliteTable("admin_sessions",{id:text("id").primaryKey(),staffId:integer("staff_id").notNull(),expiresAt:text("expires_at").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
